In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#import array as arr
#import warnings
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
#warnings.filterwarnings('ignore')
%matplotlib inline
pd.pandas.set_option('display.max_columns',None)

In [8]:
from google.colab import files
files.upload()

Saving test.csv to test (1).csv
Saving train.csv to train (1).csv


In [9]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
train=train.drop(columns=['s56','s57','s59'], axis=1)

In [10]:
train_len=len(train)
df=pd.concat([train,test], axis=0)
df=df.reset_index(drop=True)
df.head(3)

id gender s11 s12  s13 s16  \
0  b'gAAAAABinOicS09vrmgh0_JyEHihI13ptO0rCyHP7l76...      M   Y   N    1   D   
1  b'gAAAAABinOiWGC1WhR6WYP0DA5ssGv9rIekrWUwCdJ8F...      M   Y   Y    1   D   
2  b'gAAAAABinOibTcOBFIVeA4nVF3FuFz_QX3ZlPPFc21gS...      M   Y   Y    1   D   

  s17 s18  s48 s52 s53  s54  s55 s58 s69    s70 s71         n1        n2  n3  \
0   D   B    0   1      NaN   kK   B   x  op: D   b  16.144666  1.989441   2   
1   D   B    1   1      NaN  NaN   B   x  op: D   b   7.144558  0.844866   3   
2   D   B    0   1      NaN  NaN   B   x  op: D   b   6.923236  1.042018   6   

         n4         n5        n6        n7        n8        n9       n10  \
0  2.318385 -32.839277  0.017176 -9.126056  1.732291  3.698504  4.804517   
1  6.197768 -32.576597  0.013857 -9.098287  1.505885  6.791357  6.110416   
2  7.824401 -32.510544  0.013943 -9.234894  1.503828  4.109685  3.953226   

        n11  n12  n13       n14  n15  label  s56  s57  s59  
0  1.544484    0    0  0.631220    5    0.0  NaN  NaN  NaN  
1  1.712354    0    0  0.392746    3    1.0  NaN  NaN  NaN  
2  1.804260    0    0  0.222537    2    0.0  NaN  NaN  NaN

In [11]:
df.reindex()
df=df.drop(columns=['s56','s57','s59'],axis=1)

In [12]:
from sklearn.preprocessing import LabelEncoder
cols=['gender','s11','s12','s16','s17','s18','s52','s53','s54','s55','s58','s69','s70','s71']
le=LabelEncoder()
for col in cols:
    df[col]=le.fit_transform(df[col])
    df.head()

In [13]:
train1=df.iloc[:train_len,:]
test1=df.iloc[train_len:,:]

In [14]:
x=train1.drop(columns=['id','label'],axis=1)
y=train1['label']


In [15]:
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.20)

In [16]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=10)
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
from sklearn import svm
Svm=svm.SVC(probability=True)
from sklearn.ensemble import AdaBoostClassifier
ada= AdaBoostClassifier()
from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier()
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()

In [17]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_predict
from sklearn import metrics

In [18]:
VC = VotingClassifier (estimators=[('cl1', rf), ('cl5', knn), ('cl7', nb), ('cl8', dt), 
                                    ('cl9', Svm),('cl2', ada),('cl3', mlp),('cl4', lr),('cl6', gb)], weights=[2,4,2,4,2,4,2,4,2], voting='soft') 

In [19]:
def get_models():
    models = dict()
    models['Random Forest'] = rf 
    models['K Nearest Neighbor'] = knn
    models['Navie Bayes'] = nb
    models['Decision Tree'] = dt
    models['Support Vector Machine'] = Svm
    models['ADA Boost'] = ada
    models['Multi layer perception'] = mlp
    models['Gradient Boosting'] = gb
    models['Logistic Regression'] = lr
    models['Voting Classifer'] = VC
    return models   

models = get_models()
predicts=list()
names=list()

# Create a classification block
def evaluate_model(model, X, y):
    #Create Stratified K Fold
    Sfolds = StratifiedKFold(n_splits=4, shuffle=True)
    predict = cross_val_predict(model, X, y, cv=Sfolds)
    return predict

print('-----------------Accuracy List-----------------')
# Pass all model and data to classification block
for name, model in models.items():
    predict = evaluate_model(model, x, y)
    predicts.append(predict)
    names.append(name)
    print('%s: ' %(name))
    print('Predicted Class: ', predict)
    print('Accuracy: %0.2f: ' %(metrics.accuracy_score(y, predict)*100))

-----------------Accuracy List-----------------
Random Forest: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 87.75: 
K Nearest Neighbor: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 86.51: 
Navie Bayes: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 84.63: 
Decision Tree: 
Predicted Class:  [0. 0. 0. ... 0. 1. 0.]
Accuracy: 81.17: 
Support Vector Machine: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 86.85: 
ADA Boost: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 87.76: 
Multi layer perception: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 87.61: 
Gradient Boosting: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 87.87: 


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Logistic Regression: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 87.61: 


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Voting Classifer: 
Predicted Class:  [0. 0. 0. ... 0. 0. 0.]
Accuracy: 87.56: 


In [22]:
VC.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


VotingClassifier(estimators=[('cl1', RandomForestClassifier()),
                             ('cl5', KNeighborsClassifier(n_neighbors=10)),
                             ('cl7', GaussianNB()),
                             ('cl8', DecisionTreeClassifier()),
                             ('cl9', SVC(probability=True)),
                             ('cl2', AdaBoostClassifier()),
                             ('cl3', MLPClassifier()),
                             ('cl4', LogisticRegression()),
                             ('cl6', GradientBoostingClassifier())],
                 voting='soft', weights=[2, 4, 2, 4, 2, 4, 2, 4, 2])

In [23]:
pred1=VC.predict(x_test)

In [24]:
accuracy_score(y_test,pred1)

0.8796116504854369

In [26]:
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

         0.0       0.90      0.96      0.93      4740
         1.0       0.70      0.47      0.56       925

    accuracy                           0.88      5665
   macro avg       0.80      0.71      0.74      5665
weighted avg       0.87      0.88      0.87      5665



In [27]:
X_test=test1.drop(columns=['id','label'], axis=1)
X_test.head()

gender  s11  s12  s13  s16  s17  s18  s48  s52  s53  s54  s55  s58  \
28322       1    1    1    1    1    3    3    0    2    1    9    9    1   
28323       1    1    1    1    1    2    1    1    2    1    9    9    0   
28324       1    1    0    1    1    3    1    1    2    1    9    9    1   
28325       1    1    1    1    3    3    1    0    1    1    9    9    1   
28326       1    1    1    1    3    2    1    1    1    1    9    8    1   

       s69  s70  s71         n1        n2  n3        n4         n5        n6  \
28322    3    3    3  17.362752  2.985283   3  2.052415 -32.339904  0.026301   
28323    3    2    1  15.892228  2.389056   7  6.928142 -32.356092  0.010774   
28324    3    3    1  10.893303  1.470903   6  2.210629 -32.397871  0.016837   
28325    2    3    1   9.876850  1.442493   3  2.350379 -32.836003  0.015684   
28326    2    2    1  11.674406  2.544719   8  8.136887 -32.577495  0.006406   

             n7        n8         n9        n10       n11  n12  n13       n14  \
28322 -9.200175  2.122970   6.646617   4.801224  1.693087    0    0  0.439270   
28323 -8.897092  1.770889  11.046294   6.407230  1.516728    0    0  0.084334   
28324 -9.173660  1.871872   2.805834   5.481219  1.788823    0    0  0.984210   
28325 -9.178200  1.675028   6.354938   5.427266  1.792147    0    0  0.003492   
28326 -8.726633  1.963535   6.810158  11.487845  1.880992    0    0  0.060614   

       n15  
28322    2  
28323    4  
28324    0  
28325    1  
28326    0

In [28]:
pred=VC.predict(X_test)
pred

array([1., 0., 1., ..., 0., 1., 0.])

In [29]:
float_array = np.array(pred)
print(float_array)
print('After converting numpy float array to int array')
int_array = float_array.astype(int)
print(int_array)

[1. 0. 1. ... 0. 1. 0.]
After converting numpy float array to int array
[1 0 1 ... 0 1 0]


In [30]:
sub=pd.DataFrame({'id':test['id'],'label':int_array})
sub.to_csv('final submission.csv', index=False)
